### ISSUE TITLE
How to display the fingerprint dialogue

### ISSUE THREAD

**Issue by nksaroj** [Mauin/RxFingerprint#25]
Hi I am quite keen to use this library but could not find any sample to show the fingerprint dialogue

**Comment by Mauin** [comment]
RxFingerprint will only take care of the actual fingerprint authentication. You have to take care of displaying UI for the fingerprint authentication yourself. 
This choice was made to leave you with the most freedom in how you want to design your fingerprint authentication UI.

Google has posted a useful sample of how the dialog could look like [here](https://github.com/googlesamples/android-FingerprintDialog)

**Comment by nksaroj** [comment]
Thanks.
