### ISSUE TITLE
FingerprintAuthenticationException

### ISSUE THREAD

**Issue by eGorets** [Mauin/RxFingerprint#58]
I just got error log in Fabric. I don't have more information about this. Please advice me how to fix this if you can. Thanks
```
Fatal Exception: com.mtramin.rxfingerprint.data.FingerprintAuthenticationException
Vingerafdrukbewerking geannuleerd.
 Raw Text
com.mtramin.rxfingerprint.FingerprintObservable$2.onAuthenticationError (FingerprintObservable.java:98)
android.hardware.fingerprint.FingerprintManager$MyHandler.sendErrorResult (FingerprintManager.java:859)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:776)
```

**Comment by Mauin** [comment]
Which version of RxFingerprint are you using?

**Comment by eGorets** [comment]
`2.0.3`, I see you released new one. I'm updating to it right now. Also crash come from ONE PLUS A3003 phone and I can't test it

**Comment by Mauin** [comment]
Are you handling the `onError(Throwable)` callback in the Observer that you use to subscribe to RxFingerprint?

**Comment by eGorets** [comment]
Nope. I thought it had to be a pretty simple use-case.

my code is 

```

  if (RxFingerprint.isAvailable(getActivity())) {
            RxFingerprint.authenticate(getActivity())
                    .compose(this.<FingerprintAuthenticationResult>bindToLifecycle())
                    .subscribe(new Consumer<FingerprintAuthenticationResult>() {
                        @Override
                        public void accept(FingerprintAuthenticationResult fingerprintAuthenticationResult) throws Exception {
                            switch (fingerprintAuthenticationResult.getResult()) {
                                case FAILED:
                                    break;
                                case HELP:
                                    break;
                                case AUTHENTICATED:
                                    passwordAccepted();
                                    break;
                            }
                        }
                    });
        }
```

**Comment by Mauin** [comment]
You should always handle the `onError` values. In this case you're not. Now every time you dispose the RxFingerprint subscription the fingerprint sensor will report "Operation Cancelled" which will cause an `onError`. Because they're not handled at all they can crash the application.

**Comment by eGorets** [comment]
Got it. Thanks. My thought was that there was only 3 possible states of `FingerprintAuthenticationResult`. but `onError` worked only for more diff cases like megring with network calls or cryptography

**Comment by Mauin** [comment]
`onError` will get called for all events that cause the Fingerprint sensor to stop listening for fingerprint events. This can be because RxFingerprint tells it to stop, because an unknown fingerprint tried to authenticate too many times, because the sensor is broken, or other issues.

**Comment by betomaluje** [comment]
I was having this issue with the latest version 'com.mtramin:rxfingerprint:2.2.1'. After a time trying everything, I just restarted the phone (reboot) and....everything worked as normal :/

Huawei Honour 8 hahaha
