### ISSUE TITLE
Broken Link in Documentation

### ISSUE THREAD

**Issue by commonsguy** [Mauin/RxFingerprint#81]
The "see Cryptography" phrase in the [Encryption-and-decryption section](https://github.com/Mauin/RxFingerprint#encryption-and-decryption) of the documentation links to `https://github.com/Mauin/RxFingerprint#cryptography`, which does not seem to exist. Leastways, clicking that link doesn't go anywhere.

**Comment by Mauin** [comment]
Thanks for reporting this 👍 The "cryptography" section was indeed removed when I introduced RSA to RxFingerprint and rewrote the README section on encryption/decryption. I'll remove the sentence.
