### ISSUE TITLE
ActivityNotFoundException in launchFingerprintEnrollment

### ISSUE THREAD

**Issue by Flo354** [Mauin/RxFingerprint#97]
Hi,

There is an error in the following code: 
`context.startActivity(new Intent("ACTION_FINGERPRINT_ENROLL"));`

It should not be a string but a constant.
`import static android.provider.Settings.ACTION_FINGERPRINT_ENROLL;`

**Comment by Mauin** [comment]
Oh yes of course. Thanks for reporting this.
Feel free to open a quick PR with this fix. Otherwise I'll fix this for the next RC for v3.

**Comment by Mauin** [comment]
Closing this as the fix was merged into the `3.x` branch. It will be released in v3.0.0-RC-2
